version: 0.6.4-{build}

branches:
  only:
  - appveyor

image:
  - Visual Studio 2019
  - Ubuntu

init:
  - tzutil /s "W. Europe Standard Time"

install:
  - set PATH=C:\Ruby27-x64\bin
  - bundle install

for:
  -
      matrix:
        only:
          - image: Visual Studio 2019

  -
      matrix:
        only:
          - image: Ubuntu

      before_test:
        - export TZ=Europe/Berlin

build: off

test_script:
  - bundle exec rake

