version: 0.6.4-{build}

environment:
  RUBYGEMS_TOKEN:
    secure: RUnxmwed0QbCtVoP+US3z1ISjyDQ/BtMhTMJWOmTz8Hlw63FlYbs+fWbMY6YwRbb1tOLz3bKl+qqLFw8S2U4Hg==
  COVERALLS_SERVICE_NAME: appveyor
  COVERALLS_TOKEN:
    secure: cu6NcEUU479Jdkyf/qSduY/JwjsSQ8hkKZHB79UC/VY8alk1iUB1cWoBIl+Zl+Um

image:
  - Visual Studio 2019
  - Ubuntu

for:
  -
      matrix:
        only:
          - image: Visual Studio 2019

      artifacts:
        - path: '*.exe'

      install:
        - tzutil /s "W. Europe Standard Time"
        - set PATH=C:\Ruby30-x64\bin
        - bundle install

      build_script:
        - bundle exec rake buildsingle
        - rake buildexe

      test_script:
        - bundle exec rake test
        - bundle exec rake testsingle
        - bundle exec rake testexe

  -
      matrix:
        only:
          - image: Ubuntu

      artifacts:
        - path: '*.rb'
        - path: '*.gem'

      install:
        - export TZ=Europe/Berlin
        - bundle install

      build_script:
        - bundle exec rake buildsingle
        - bundle exec rake buildgem

      test_script:
        - COVERALLS_REPO_TOKEN=${COVERALLS_TOKEN} bundle exec rspec spec/test_default.rb
        - bundle exec rake testsingle

      before_deploy:
        - sh: "echo -e \"---\n:rubygems_api_key: ${RUBYGEMS_TOKEN}\" > ~/.gem/credentials"
        - chmod 0600 ~/.gem/credentials
        - gem push *.gem

before_build:
  - bundle exec rake check

before_test:
  - ruby -v
  - gem -v
  - bundle -v

deploy:
  - provider: GitHub
    auth_token:
      secure: M1W91LySSlC/6n0+CCIfUhxfPu5DqG60KVdelbOCtYDUekkMyLj7RxLyEdLQYpAy
    artifact: /.*\.(?:gem|exe|rb)/
    draft: true
    on:
      APPVEYOR_REPO_TAG: true
