version: 0.6.4-{build}

branches:
  only:
  - appveyor

install:
  - set PATH=C:\Ruby27-x64\bin
  - bundle install

environment:
  matrix:
    - job name: Windows
      appveyor_build_worker_image: Visual Studio 2019
    - job name: Linux
      appveyor_build_worker_image: Ubuntu

for:
  -
      matrix:
        only:
          - job_name: Windows

      before_test:
        - tzutil /s "W. Europe Standard Time"

  -
      matrix:
        only:
          - job_name: Linux

      before_test:
        - export TZ=Europe/Berlin

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake

