version: 0.6.4-{build}

branches:
  only:
  - appveyor

image:
  - Visual Studio 2019
  - Ubuntu

for:
  -
      matrix:
        only:
          - image: Visual Studio 2019

      install:
        - tzutil /s "W. Europe Standard Time"
        - set PATH=C:\Ruby27-x64\bin
        - bundle install

      build_script:
        - rake buildexe

  -
      matrix:
        only:
          - image: Ubuntu

      install:
        - export TZ=Europe/Berlin
        - bundle install

      build_script:
        - bundle exec rake buildsingle

before_build:
  - bundle exec rake check
  - bundle exec rake preparebuild

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake test

