version: 0.6.4-{build}

branches:
  only:
  - appveyor

image:
  - Visual Studio 2019
  - Ubuntu

for:
  -
      matrix:
        only:
          - image: Visual Studio 2019
      install:
        - tzutil /s "W. Europe Standard Time"
        - set PATH=C:\Ruby27-x64\bin
        - bundle install

  -
      matrix:
        only:
          - image: Ubuntu

      install:
        - export TZ=Europe/Berlin
        - bundle install

build: off

test_script:
  - bundle exec rake

