version: 0.6.4-{build}

branches:
  only:
  - appveyor

image:
  - Visual Studio 2019
  - Ubuntu

for:
  -
      matrix:
        only:
          - image: Visual Studio 2019

      artifacts:
        - path: '*.exe'

      install:
        - tzutil /s "W. Europe Standard Time"
        - set PATH=C:\Ruby27-x64\bin
        - bundle install

      build_script:
        - rake buildexe

      test_script:
        - bundle exec rake testexe

  -
      matrix:
        only:
          - image: Ubuntu

      artifacts:
        - path: '*.rb'
        - path: '*.gem'

      install:
        - export TZ=Europe/Berlin
        - bundle install

      build_script:
        - bundle exec rake buildsingle
        - bundle exec rake buildgem

      test_script:
        - bundle exec rake test
        - bundle exec rake testsingle

before_build:
  - bundle exec rake check
  - bundle exec rake preparebuild

before_test:
  - ruby -v
  - gem -v
  - bundle -v

deploy:
  provider: GitHub
  auth_token:
    secure: M1W91LySSlC/6n0+CCIfUhxfPu5DqG60KVdelbOCtYDUekkMyLj7RxLyEdLQYpAy
  artifact: /.*\.(?:gem|exe|rb)/
  draft: true

